### ISSUE TITLE
Getting Fiber/bindEnvironment error in Meteor 1.3 beta 7

### ISSUE THREAD

**Issue by huttonr** [peerlibrary/meteor-server-autorun#10]
In using `peerlibrary:server-autorun` with Meteor 1.3-modules-beta.7 I get the following server error when a user requests a webpage:

```
E20160205-10:55:38.281(-8) (webapp_server.js:716) Error running template: Error: Meteor
code must always run within a Fiber. Try wrapping callbacks that you pass to non-Meteor
libraries with Meteor.bindEnvironment.
```

**Comment by mitar** [comment]
OK, this commit is the problem: https://github.com/meteor/meteor/commit/5d501d17936de234fa0e992e590f70bf958e98db

Before, stack trace for calling `getBoilerplate` was:

```
Object.handle (packages/webapp/webapp_server.js:708:1)
next (meteor/packages/webapp/.npm/package/node_modules/connect/lib/proto.js:190:15)
next (meteor/packages/webapp/.npm/package/node_modules/connect/lib/proto.js:192:9)
next (meteor/packages/webapp/.npm/package/node_modules/connect/lib/proto.js:127:23)
Function.app.handle (meteor/packages/webapp/.npm/package/node_modules/connect/lib/proto.js:198:3)
Object.fn [as handle] (meteor/packages/webapp/.npm/package/node_modules/connect/lib/proto.js:74:14)
next (meteor/packages/webapp/.npm/package/node_modules/connect/lib/proto.js:190:15)
Object.WebAppInternals.staticFilesMiddleware (packages/webapp/webapp_server.js:362:1)
packages/webapp/webapp_server.js:634:1
```

After upgrade of dependencies it is:

```
at Object.handle (packages/webapp/webapp_server.js:714:1)
at next (meteor/packages/webapp/.npm/package/node_modules/connect/lib/proto.js:174:15)
at Object.next (meteor/packages/webapp/.npm/package/node_modules/connect/lib/proto.js:176:9)
at Object.immediate._onImmediate (timers.js:381:16)
at processImmediate [as _immediateCallback] (timers.js:363:15)
```

So, [fiber wrapping here](https://github.com/meteor/meteor/blob/devel/packages/webapp/webapp_server.js#L627) is not in the effect anymore. I will open a ticket at Meteor.

**Comment by mitar** [comment]
Reported as https://github.com/meteor/meteor/issues/6170.

**Comment by mitar** [comment]
This has been fixed in Meteor in `devel` branch.
